budget/urls.py
from django.urls import path
from . import views
from .views import PlanListView, PlanDetailView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(PlanListView.as_view()), name='budget-home'), 
    path('create_plan/', views.create_plan, name='budget-plan-creation'),
    path('create_ticket/', views.create_ticket, name='ticket-creation'), 
    path('plan/<int:pk>/', PlanDetailView.as_view(), name='plan-detail'),
    path('tickets/', views.display_tickets, name='view-tickets'),
    path('budget_deposit/', views.create_transaction, name='budget-deposit'),
    path('transaction_report/', views.transaction_report, name='transaction-report')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget.urls')),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('profile/', user_views.profile, name='profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.register, name='register')
]

budget/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models
from django.utils import timezone


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    balance = models.FloatField() # Balance in specific category

    def __str__(self):
        return f"{self.name} - ${self.balance:.2f}"

class Plan(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

class PlanRow(models.Model):
    choice = (
        ("Dollar Amount", "Dollar Amount"),
        ("Percentage", "Percentage")
    )

    category = models.ForeignKey(Category, on_delete=models.SET("Category Deleted"))
    value_type = models.CharField("Type", max_length = 100, choices=choice)
    value_num = models.FloatField()
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.plan.name} : {self.category.name} - Value Type: {self.value_type} -- Value Percent/Amount: {self.value_num}"


class PlanTransaction(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE) # The plan that is being applied
    transAmount = models.FloatField() # Amount to be budgeted
    date_posted = models.DateTimeField(default=timezone.now) # Date of Transaction
    def __str__(self):
        return f"Date: {self.date_posted} | Plan: {self.plan} | Amount: {self.transAmount}"


# Data has to come from the views.py file which is a part of the (FRONTEND) task
class CategoryTransaction(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET("Category Deleted"))
    catAmount = models.FloatField() # The amount budgeted in said category
    planTotalTran = models.ForeignKey(PlanTransaction, on_delete=models.CASCADE) # Connects to the Transaction

    def __str__(self):
        return f"Category: {self.category} | Amount: {self.catAmount}"
        

class Ticket(models.Model):
    category = models.CharField(max_length=255)
    spending_limit = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now_add = True)  

    def __str__(self):
        return f"{self.category} - {self.description}"

budget/forms.py
from django import forms
from django.forms import ModelForm
from .models import PlanRow, Plan, PlanTransaction, Category

class PlanRowCreation(ModelForm):

    class Meta:
        model = PlanRow
        fields = ['category', 'value_type', 'value_num', 'plan']

class GetPlan(ModelForm):
    availablePlans = []
    for plan in Plan.objects.all():
        availablePlans.append((plan.name, plan.name))
    print(availablePlans)
    planName = forms.ChoiceField(choices=availablePlans, label="Plan Name")

    class Meta:
        model = Plan
        fields = ['planName']
    
class CreateTicketForm(forms.Form):
    category = forms.CharField(label="Category", max_length=255)
    spending_limit = forms.DecimalField(label="Spending Limit", max_digits=10, decimal_places=2)
    description = forms.CharField(label="Description of Purchase", widget=forms.Textarea)

class BudgetTransaction(ModelForm):
    class Meta:
        model = PlanTransaction
        fields = ['plan', 'transAmount']

class CreateCategory(ModelForm):

    class Meta:
        model = Category
        fields = "__all__"

class CreatePlan(ModelForm):

    class Meta:
        model = Plan
        fields = "__all__"

budget/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Plan, PlanRow
from .models import Ticket, PlanTransaction, CategoryTransaction, Category
from .forms import PlanRowCreation, GetPlan, BudgetTransaction, CreateCategory, CreatePlan
from django.contrib import messages
from .forms import CreateTicketForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from .calculations import Calculations


# Create your views here.


# given how ListView works in Django, I pass in two template lists through one view: one for plan and other for ticket

class PlanListView(ListView):
    model = Plan
    template_name = 'budget/home.html'
    context_object_name = 'budget'
    
    def get_context_data(self):
        context = super(PlanListView, self).get_context_data()
        
        context['plan_list'] = Plan.objects.filter(user=self.request.user)
        context['ticket_list'] = Ticket.objects.filter(user=self.request.user)

        return context


class PlanDetailView(DetailView):
    model = Plan


@login_required
def create_ticket(request):
    form = CreateTicketForm()
    if request.method == 'POST':
        form = CreateTicketForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data['category']
            spending_limit = form.cleaned_data['spending_limit']
            description = form.cleaned_data['description']
            user = request.user
            ticket = Ticket(category=category, spending_limit=spending_limit, description=description, user = user)
            ticket.save()
            return redirect('budget-home')   
    else:
        form = CreateTicketForm()
    return render(request, 'budget/create_ticket.html', {'form': form})

@login_required
def display_tickets(request):
    tickets = request.user.ticket_set.all();
    return render(request, 'budget/tickets.html', {'tickets': tickets})

@login_required
def create_plan(request):
    plans = GetPlan()
    # PLAN ROW
    if request.method == "POST":
        if "submit-row" in request.POST:  # the user submitted a new plan row
            rowform = PlanRowCreation(request.POST)
            if rowform.is_valid():
                category = rowform.cleaned_data['category']
                value_type = rowform.cleaned_data['value_type']
                value_num = rowform.cleaned_data['value_num']
                plan = rowform.cleaned_data['plan']
                user = request.user
                pr = PlanRow(category=category, value_type=value_type, value_num=value_num, plan=plan, user=user)
                pr.save()
                messages.success(request, f'Budget successfully added')
                return redirect('budget-plan-creation')
            
    # # VIEW PLANS
    #     elif "select-plan" in request.POST:
    #         rowform = PlanRowCreation()
    #         catform = CreateCategory()
    #         planform = CreatePlan()
    #         # getting all the rows under the selected plan
    #         allPlanRows = PlanRow.objects.filter(plan__name=request.POST['planName'])
    #         return render(request, 'budget/create_plan.html', {'rowform':rowform, 'catform':catform, 'planform':planform, 'plans':plans, 'rowData': allPlanRows})

    # Create Category
        elif "submit-category" in request.POST:  
            catform = CreateCategory(request.POST) 
            if catform.is_valid():
                catform.save() # Category officially saved
                messages.success(request, f'Category Created')
                return redirect('budget-plan-creation')

    # Create Plan
        elif "submit-plan" in request.POST:  
            planform = CreatePlan()
            if planform.is_valid():
                planform.save() # Plan officially saved
                messages.success(request, f'Plan Created')
                return redirect('budget-plan-creation')
                
    else:
        rowform = PlanRowCreation()
        catform = CreateCategory()
        planform = CreatePlan()

    return render(request, 'budget/create_plan.html', {'rowform':rowform, 'catform':catform, 'planform':planform, 'plans':plans})

@login_required
def create_transaction(request):
    if request.method == "POST":
        if "submit-deposit" in request.POST:  # the user submitted a new transaction
            form = BudgetTransaction(request.POST) 
            if form.is_valid():
                form.save() # Transaction officially saved
                trans = PlanTransaction.objects.last() # Transactions just submitted
                for row in PlanRow.objects.filter(plan__name=trans.plan): # Going through every row within the plan
                    pOrD = True if row.value_type == "Percentage" else False # Percent or Dollar Amount        
                    cat = row.category
                    processCatBudget = Calculations.budget(cat, row.value_num, pOrD, trans.transAmount)
                    
                    # Creating the Category transaction to save
                    catTrans = CategoryTransaction(category = cat, catAmount = processCatBudget[cat], planTotalTran = trans)
                    catTrans.save() # Saved

                    updatedCat = Category.objects.filter(name=row.category.name, balance=row.category.balance)[0]
                    oldBalance = updatedCat.balance
                    updatedCat.balance = oldBalance + processCatBudget[cat]
                    updatedCat.save()

                messages.success(request, f'Amount Budgeted') # Confirmation
                return redirect('transaction-report')

    else:
        form = BudgetTransaction()

    return render(request, 'budget/budget_deposit.html', {'form':form})

@login_required
def transaction_report(request):
    context = {
        'transaction': PlanTransaction.objects.last(),
        'catTransactions': CategoryTransaction.objects.filter(planTotalTran=PlanTransaction.objects.last())
    }
    return render(request, 'budget/transaction_report.html', context)

budget/templates/budget/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>

<html>
    <head>
        <!-- Bootstrap Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>Welcome</title>
        {% endif %}

        <link rel="stylesheet" href="{% static 'budget/main.css' %}">
        {% block head %}
        
        {% endblock %}
        
    </head>

    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'budget-home' %}">CommonCents</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'budget-plan-creation' %}">Create Plan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'budget-deposit' %}">Deposit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'ticket-creation' %}">Create Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'view-tickets' %}">View Ticket</a>
                        </li>
                        
                    </ul>
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link" aria-current="page" href="/profile">Profile</a>
                        <a class="nav-link" aria-current="page" href="/logout">Logout</a>
                    {% else %}
                        <a class="nav-link" aria-current="page" href="/login">Login</a>
                        <a class="nav-link" aria-current="page" href="/register">Register</a>
                    {% endif %}
                </div>

            </div>
        </nav>
        
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="container   ">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Required BootStrap Js Bundle with Popper -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

budget/templates/budget/budget_deposit.html
{% extends 'budget/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h4 class="card-title">Deposit</h4>
                </div>
                <div class="card-body">     
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" name="submit-deposit" class="btn btn-success">Deposit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

budget/templates/budget/create_plan.html
{% extends 'budget/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h4 class="card-title">Create New Category</h4>
                </div>
                <div class="card-body">     
                    <form action="" method="post">
                        {% csrf_token %}
                        {{catform|crispy}}
                        <button type="submit" name="submit-category" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="row justify-content-center mt-5">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h4 class="card-title">Edit Existing Budget Plans</h4>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{rowform|crispy}}
                        <button type="submit" name="submit-row" class="btn btn-success">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

budget/templates/budget/create_ticket.html
{% extends 'budget/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h4 class="card-title">Create Ticket</h4>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-success" style="display: block;">Create</button>
                        <a href="{% url 'budget-home' %}" class="card-link badge badge-pill badge-dark mt-3"">View Existing Tickets</a>
                    </form>
                </div>
            </div>
        </div>
    </div>  
{% endblock %}

budget/templates/budget/home.html
{% extends 'budget/base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-9">
            {% for plan in  plan_list %}
                <div class="row mb-3">
                    <div class="col-12">
                        <button class="btn btn-primary col" type="button" data-toggle="collapse" data-target="#show_content_{{ plan.id }}" aria-expanded="false" aria-controls="collapseExample">
                            {{ plan.name }}
                        </button>
                    </div>
                    <div class="collapse col-12 show" id="show_content_{{ plan.id }}">
                        <div class="card card-body">
                            <ul class="list-group list-group-flush">
                                {% for planrow in plan.planrow_set.all %}
                                    <li class="list-group-item">
                                        <div class="row py-1">
                                            <h5>{{ planrow.category.name }}</h5>  
                                        </div>
                                        <div class="row py-1">
                                            Amount saved from each deposit: 
                                            {% if planrow.value_type == "Dollar Amount" %}
                                                ${{ planrow.value_num|floatformat:2 }} 
                                            {% endif %}
                                            {% if planrow.value_type == "Percentage" %}
                                                {{ planrow.value_num|floatformat:2 }}%
                                            {% endif %}
                                        </div>
                                        <div class="row py-1">
                                            Amount balanced so far: ${{ planrow.category.balance|floatformat:2 }}
                                        </div>
                                    </li>
                                {% endfor %}
                              </ul>
                        </div>
                    </div>
                    
                </div>
            {% endfor %}
        </div>
        <div class="col-3">
            {% for ticket in ticket_list %}
                <div class="card mb-3">
                    <h5 class="card-header"> {{ ticket.category }}</h5>
                    <div class="card-body">
                        <p class="card-text">Purchase Amount: ${{ ticket.spending_limit }} </p>
                        <p class="card-text"> {{ ticket.description }} </p>
                        <footer class="blockquote-footer"> {{ ticket.date_created }}</footer>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

budget/templates/budget/plan_detail.html
{% extends 'budget/base.html' %}

{% block content %}

<div class="row justify-content-center mt-3">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-dark text-white text-center pt-1 pb-0">
                <h4>{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for planrow in object.planrow_set.all %}
                        <li class="list-group-item">
                            <div class="row py-1">
                                {{ planrow.name }}  
                            </div>
                            <div class="row py-1">
                                {{ planrow.category }}  
                            </div>
                            <div class="row py-1">
                                {{ planrow.value_num }}  
                            </div>
                        </li>
                    {% endfor %}
                  </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

budget/templates/budget/tickets.html
{% extends 'budget/base.html' %} 

{% block content %} 

    <a href="{% url 'ticket-creation' %}"> Create new ticket! </a>
    {% for ticket in tickets %} 
    <!-- created empty divs to make things easier for the CSS specific task -->
    <div>
        {{ ticket.category }}
    </div>

    <div>
        {{ ticket.spending_limit }}
    </div>

    <div>
        {{ ticket.description }}
    </div>

    <div>
        {{ ticket.date_created }}
    </div>
    <br>
    {% endfor %}
{% endblock %}

budget/templates/budget/transaction_report.html
{% extends 'budget/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'budget/transaction_report.css' %}">
{% endblock %}
    {% block content %}
        <!-- <div>
            <h1><strong>Transaction: </strong>{{transaction.date_posted}}</h1>
            <div>
                <h2>Plan: {{transaction.plan.name}}</h2>
                <h3>Amount: ${{transaction.transAmount|floatformat:2}}</h3>
                <div>
                    <div class = "cat-column">
                        <p><strong>Category: </strong></p>
                        <p>Amount Deposited: </p>
                        <p>Current Balance: </p>
                    </div>
                    {% for catTrans in catTransactions %}
                        <div class = "cat-column">
                            <p><strong>{{catTrans.category.name}}</strong></p>
                            <p>${{catTrans.catAmount|floatformat:2}}</p>
                            <p>${{catTrans.category.balance|floatformat:2}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div> -->

        <div class="card mt-3">
            <h2 class="card-header bg-info text-white"><strong>Transaction: </strong>{{transaction.date_posted}}</h1>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col">
                        <h4>Plan: {{transaction.plan.name}}</h4>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col">
                        <h4>Amount: ${{transaction.transAmount|floatformat:2}}</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <p><strong>Category: </strong></p>
                        <p>Amount Deposited: </p>
                        <p>Current Balance: </p>
                    </div>
                    {% for catTrans in catTransactions %}
                        <div class="col border border-dark rounded mr-2">
                            <p><strong>{{catTrans.category.name}}</strong></p>
                            <p>${{catTrans.catAmount|floatformat:2}}</p>
                            <p>${{catTrans.category.balance|floatformat:2}}</p>
                        </div>
                    {% endfor %}
                </div>
        </div>
    {% endblock content %}